"""add drone shares, rename columns, fk ondelete

Revision ID: 428736f55d32
Revises: 4cb30811acf4
Create Date: 2026-06-22 11:56:41.291306

Manually adjusted the output of `alembic revision --autogenerate`:
- Autogenerate can't detect a column rename, so it emitted DROP + ADD pairs for
  every renamed column. Adding a NOT NULL column with no default to a non-empty
  table fails, and even if it didn't, dropping the old column would
  discard its data. Every such pair was replaced with an in-place
  `op.alter_column(..., new_column_name=...)`, which preserves the data.
- In Postgres a column rename carries its dependent index / unique constraint /
  foreign key along automatically, but those keep their OLD names — so they're
  explicitly renamed here to match the new column (keeps future autogenerate
  runs from flagging the name drift).
- `ON DELETE` can't be altered in place, so the drone owner FK is dropped and
  recreated; that's how it gains `ondelete=CASCADE`.
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "428736f55d32"
down_revision: Union[str, Sequence[str], None] = "4cb30811acf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- drone_share: brand-new table (autogenerated as-is; correct) ----------
    # The FK delete rules are baked into the CREATE: a share dies with its drone
    # (CASCADE) and survives its minter's deletion with a null minter (SET NULL).
    op.create_table(
        "drone_share",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("drone_id", sa.Uuid(), nullable=False),
        sa.Column("creation_user_id", sa.Uuid(), nullable=True),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("creation_timestamp", sa.DateTime(), nullable=False),
        sa.Column("expiration_timestamp", sa.DateTime(), nullable=False),
        sa.Column("revocation_timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["creation_user_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["drone_id"], ["drone.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_drone_share_drone_id"), "drone_share", ["drone_id"], unique=False
    )
    op.create_index(
        op.f("ix_drone_share_token_hash"), "drone_share", ["token_hash"], unique=True
    )

    # --- drone: rename columns IN PLACE (preserves data) ----------------------
    # Replaces the autogenerated add-NOT-NULL + drop pairs, which would have
    # failed on the non-empty table and discarded the existing values.
    op.alter_column("drone", "owner_id", new_column_name="creation_user_id")
    op.alter_column("drone", "created_at", new_column_name="creation_timestamp")
    op.alter_column("drone", "updated_at", new_column_name="update_timestamp")
    # The rename moved these onto the new column but kept their old names — give
    # them the matching names so a future autogenerate stays quiet.
    op.execute("ALTER INDEX ix_drone_owner_id RENAME TO ix_drone_creation_user_id")
    op.execute(
        "ALTER TABLE drone RENAME CONSTRAINT "
        "drone_name_owner_id_key TO drone_name_creation_user_id_key"
    )
    # ON DELETE can't be altered in place → drop + recreate to add CASCADE.
    op.drop_constraint("drone_owner_id_fkey", "drone", type_="foreignkey")
    op.create_foreign_key(
        "drone_creation_user_id_fkey",
        "drone",
        "user",
        ["creation_user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # --- user: rename columns in place (plain columns, no dependents) ----------
    op.alter_column("user", "created_at", new_column_name="creation_timestamp")
    op.alter_column("user", "updated_at", new_column_name="update_timestamp")


def downgrade() -> None:
    """Downgrade schema (symmetric in-place reverses; no data loss)."""
    # Reverse the user renames.
    op.alter_column("user", "creation_timestamp", new_column_name="created_at")
    op.alter_column("user", "update_timestamp", new_column_name="updated_at")

    # Reverse drone: drop the CASCADE FK, rename columns back, restore the
    # original index/constraint names, then recreate the FK in its original
    # (no delete rule) state.
    op.drop_constraint("drone_creation_user_id_fkey", "drone", type_="foreignkey")
    op.alter_column("drone", "creation_user_id", new_column_name="owner_id")
    op.alter_column("drone", "creation_timestamp", new_column_name="created_at")
    op.alter_column("drone", "update_timestamp", new_column_name="updated_at")
    op.execute("ALTER INDEX ix_drone_creation_user_id RENAME TO ix_drone_owner_id")
    op.execute(
        "ALTER TABLE drone RENAME CONSTRAINT "
        "drone_name_creation_user_id_key TO drone_name_owner_id_key"
    )
    op.create_foreign_key("drone_owner_id_fkey", "drone", "user", ["owner_id"], ["id"])

    # Drop drone_share.
    op.drop_index(op.f("ix_drone_share_token_hash"), table_name="drone_share")
    op.drop_index(op.f("ix_drone_share_drone_id"), table_name="drone_share")
    op.drop_table("drone_share")
