"""hash drone secret

Revision ID: 5382982b0a02
Revises: 428736f55d32
Create Date: 2026-06-22 14:43:32.294403

Manually adjusted the output of `alembic revision --autogenerate`:
- Autogenerate can't see that `secret_key` was renamed to `secret_hash`; it
  emitted an add (NOT NULL, no default) + drop, which would fail on the
  non-empty table and discard every existing secret. Replaced with an in-place
  `op.alter_column(..., new_column_name=...)` that preserves the column.
- After the rename the column still holds the PLAINTEXT secrets, so a data
  migration hashes them in place (SHA-256, mirroring app.utils.sha256_hex,
  inlined so this revision stays frozen). Deployed companions keep
  authenticating untouched: they still send the plaintext, which now hashes to
  the stored value.
- Hashing is one-way, so `downgrade` can only rename the column back — the
  original plaintext is unrecoverable (see the note there).
"""

import hashlib
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5382982b0a02"
down_revision: Union[str, Sequence[str], None] = "428736f55d32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Rename in place (preserves the column and its values) instead of the
    # autogenerated add-NOT-NULL + drop, which would fail and lose data.
    op.alter_column("drone", "secret_key", new_column_name="secret_hash")

    # The renamed column still holds plaintext — hash each value in place so the
    # column ends up storing only SHA-256 digests (identical to sha256_hex()).
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, secret_hash FROM drone")).fetchall()
    for drone_id, plaintext in rows:
        conn.execute(
            sa.text("UPDATE drone SET secret_hash = :hash WHERE id = :id"),
            {"hash": hashlib.sha256(plaintext.encode()).hexdigest(), "id": drone_id},
        )


def downgrade() -> None:
    """Downgrade schema.

    Hashing is one-way: the original plaintext secrets cannot be restored. This
    only renames the column back; the values remain SHA-256 hashes, so every
    drone's secret would have to be re-provisioned (rotated) to authenticate
    again under the old plaintext-comparison code.
    """
    op.alter_column("drone", "secret_hash", new_column_name="secret_key")
