[project]
name = "drone_grid_companion"
version = "0.1.0"
description = "Companion program that connects a MAVLink flight controller and camera to a Drone Grid instance"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aioconsole>=0.8.2",
    "mavsdk>=3.15.3",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
    "websockets>=14.0",
]
