/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as ShareTokenRouteImport } from './routes/shares.$token'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutDronesRouteImport } from './routes/_layout/drones'
import { Route as LayoutSharesRouteImport } from './routes/_layout/shares'
import { Route as LayoutDronesDroneIdRouteImport } from './routes/_layout/drones_.$droneId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/shares/$token',
  path: '/shares/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDronesRoute = LayoutDronesRouteImport.update({
  id: '/drones',
  path: '/drones',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSharesRoute = LayoutSharesRouteImport.update({
  id: '/shares',
  path: '/shares',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDronesDroneIdRoute = LayoutDronesDroneIdRouteImport.update({
  id: '/drones_/$droneId',
  path: '/drones/$droneId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/drones': typeof LayoutDronesRoute
  '/shares': typeof LayoutSharesRoute
  '/': typeof LayoutIndexRoute
  '/drones/$droneId': typeof LayoutDronesDroneIdRoute
  '/shares/$token': typeof ShareTokenRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesByTo {
  '/drones': typeof LayoutDronesRoute
  '/shares': typeof LayoutSharesRoute
  '/': typeof LayoutIndexRoute
  '/drones/$droneId': typeof LayoutDronesDroneIdRoute
  '/shares/$token': typeof ShareTokenRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/drones': typeof LayoutDronesRoute
  '/_layout/shares': typeof LayoutSharesRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/drones_/$droneId': typeof LayoutDronesDroneIdRoute
  '/shares/$token': typeof ShareTokenRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/drones' | '/shares' | '/' | '/drones/$droneId' | '/shares/$token' | '/terms' | '/privacy'
  fileRoutesByTo: FileRoutesByTo
  to: '/drones' | '/shares' | '/' | '/drones/$droneId' | '/shares/$token' | '/terms' | '/privacy'
  id: '__root__' | '/_layout' | '/_layout/drones' | '/_layout/shares' | '/_layout/' | '/_layout/drones_/$droneId' | '/shares/$token' | '/terms' | '/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ShareTokenRoute: typeof ShareTokenRoute
  TermsRoute: typeof TermsRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/drones': {
      id: '/_layout/drones'
      path: '/drones'
      fullPath: '/drones'
      preLoaderRoute: typeof LayoutDronesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shares': {
      id: '/_layout/shares'
      path: '/shares'
      fullPath: '/shares'
      preLoaderRoute: typeof LayoutSharesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/drones_/$droneId': {
      id: '/_layout/drones_/$droneId'
      path: '/drones/$droneId'
      fullPath: '/drones/$droneId'
      preLoaderRoute: typeof LayoutDronesDroneIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/shares/$token': {
      id: '/shares/$token'
      path: '/shares/$token'
      fullPath: '/shares/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutDronesRoute: typeof LayoutDronesRoute
  LayoutSharesRoute: typeof LayoutSharesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDronesDroneIdRoute: typeof LayoutDronesDroneIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDronesRoute: LayoutDronesRoute,
  LayoutSharesRoute: LayoutSharesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDronesDroneIdRoute: LayoutDronesDroneIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ShareTokenRoute: ShareTokenRoute,
  TermsRoute: TermsRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
