/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as ShareTokenRouteImport } from './routes/shares.$token'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutDronesRouteImport } from './routes/_layout/drones'
import { Route as LayoutDronesDroneIdRouteImport } from './routes/_layout/drones_.$droneId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/shares/$token',
  path: '/shares/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDronesRoute = LayoutDronesRouteImport.update({
  id: '/drones',
  path: '/drones',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDronesDroneIdRoute = LayoutDronesDroneIdRouteImport.update({
  id: '/drones_/$droneId',
  path: '/drones/$droneId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/drones': typeof LayoutDronesRoute
  '/': typeof LayoutIndexRoute
  '/drones/$droneId': typeof LayoutDronesDroneIdRoute
  '/shares/$token': typeof ShareTokenRoute
}
export interface FileRoutesByTo {
  '/drones': typeof LayoutDronesRoute
  '/': typeof LayoutIndexRoute
  '/drones/$droneId': typeof LayoutDronesDroneIdRoute
  '/shares/$token': typeof ShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/drones': typeof LayoutDronesRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/drones_/$droneId': typeof LayoutDronesDroneIdRoute
  '/shares/$token': typeof ShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/drones' | '/' | '/drones/$droneId' | '/shares/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/drones' | '/' | '/drones/$droneId' | '/shares/$token'
  id: '__root__' | '/_layout' | '/_layout/drones' | '/_layout/' | '/_layout/drones_/$droneId' | '/shares/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/drones': {
      id: '/_layout/drones'
      path: '/drones'
      fullPath: '/drones'
      preLoaderRoute: typeof LayoutDronesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/drones_/$droneId': {
      id: '/_layout/drones_/$droneId'
      path: '/drones/$droneId'
      fullPath: '/drones/$droneId'
      preLoaderRoute: typeof LayoutDronesDroneIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/shares/$token': {
      id: '/shares/$token'
      path: '/shares/$token'
      fullPath: '/shares/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutDronesRoute: typeof LayoutDronesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDronesDroneIdRoute: typeof LayoutDronesDroneIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDronesRoute: LayoutDronesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDronesDroneIdRoute: LayoutDronesDroneIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
