// This file is auto-generated by @hey-api/openapi-ts

export const DroneCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DroneCreate'
} as const;

export const DroneResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        creation_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Creation User Id'
        },
        creation_timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Creation Timestamp'
        },
        update_timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Update Timestamp'
        },
        stream_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stream Url'
        }
    },
    type: 'object',
    required: ['id', 'name', 'creation_user_id', 'creation_timestamp', 'update_timestamp'],
    title: 'DroneResponse'
} as const;

export const DroneSecretResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        creation_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Creation User Id'
        },
        creation_timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Creation Timestamp'
        },
        update_timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Update Timestamp'
        },
        stream_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stream Url'
        },
        secret: {
            type: 'string',
            title: 'Secret'
        }
    },
    type: 'object',
    required: ['id', 'name', 'creation_user_id', 'creation_timestamp', 'update_timestamp', 'secret'],
    title: 'DroneSecretResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ShareCreateSchema = {
    properties: {
        label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        ttl_hours: {
            type: 'integer',
            maximum: 24,
            minimum: 1,
            title: 'Ttl Hours',
            default: 2
        }
    },
    type: 'object',
    title: 'ShareCreate'
} as const;

export const ShareCreatedResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        token: {
            type: 'string',
            title: 'Token'
        },
        expiration_timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Expiration Timestamp'
        }
    },
    type: 'object',
    required: ['id', 'token', 'expiration_timestamp'],
    title: 'ShareCreatedResponse'
} as const;

export const ShareResolvedResponseSchema = {
    properties: {
        drone_id: {
            type: 'string',
            format: 'uuid',
            title: 'Drone Id'
        }
    },
    type: 'object',
    required: ['drone_id'],
    title: 'ShareResolvedResponse',
    description: 'The additional data that the user needs to view the streams.'
} as const;

export const ShareResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        creation_timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Creation Timestamp'
        },
        expiration_timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Expiration Timestamp'
        }
    },
    type: 'object',
    required: ['id', 'label', 'creation_timestamp', 'expiration_timestamp'],
    title: 'ShareResponse'
} as const;

export const UserSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sub: {
            type: 'string',
            title: 'Sub'
        },
        issuer: {
            type: 'string',
            title: 'Issuer'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        is_admin: {
            type: 'boolean',
            title: 'Is Admin',
            default: false
        },
        creation_timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Creation Timestamp'
        },
        update_timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Update Timestamp'
        }
    },
    type: 'object',
    required: ['sub', 'issuer', 'email'],
    title: 'User'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;