// This file is auto-generated by @hey-api/openapi-ts

export const DroneCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DroneCreate'
} as const;

export const DroneResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        secret_key: {
            type: 'string',
            title: 'Secret Key'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        stream_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stream Url'
        }
    },
    type: 'object',
    required: ['id', 'name', 'secret_key', 'owner_id', 'created_at', 'updated_at'],
    title: 'DroneResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MediaMtxAuthRequestModelSchema = {
    properties: {
        user: {
            type: 'string',
            title: 'User'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        token: {
            type: 'string',
            title: 'Token'
        },
        action: {
            type: 'string',
            enum: ['publish', 'read'],
            title: 'Action'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        protocol: {
            type: 'string',
            enum: ['rtsp', 'webrtc'],
            title: 'Protocol'
        }
    },
    type: 'object',
    required: ['user', 'password', 'token', 'action', 'path', 'protocol'],
    title: 'MediaMtxAuthRequestModel'
} as const;

export const UserSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sub: {
            type: 'string',
            title: 'Sub'
        },
        issuer: {
            type: 'string',
            title: 'Issuer'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        is_admin: {
            type: 'boolean',
            title: 'Is Admin',
            default: false
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['sub', 'issuer', 'email'],
    title: 'User'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;