// This file is auto-generated by @hey-api/openapi-ts

export const DroneCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DroneCreate'
} as const;

export const DroneResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        secret_key: {
            type: 'string',
            title: 'Secret Key'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        stream_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stream Url'
        }
    },
    type: 'object',
    required: ['id', 'name', 'secret_key', 'owner_id', 'created_at', 'updated_at'],
    title: 'DroneResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ShareCreateSchema = {
    properties: {
        label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        ttl_hours: {
            type: 'integer',
            maximum: 24,
            minimum: 1,
            title: 'Ttl Hours',
            default: 2
        }
    },
    type: 'object',
    title: 'ShareCreate'
} as const;

export const ShareCreatedSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        token: {
            type: 'string',
            title: 'Token'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['id', 'token', 'expires_at'],
    title: 'ShareCreated',
    description: 'Returned once at creation — the only time the plaintext token is exposed.'
} as const;

export const ShareResolvedSchema = {
    properties: {
        drone_id: {
            type: 'string',
            format: 'uuid',
            title: 'Drone Id'
        },
        drone_name: {
            type: 'string',
            title: 'Drone Name'
        }
    },
    type: 'object',
    required: ['drone_id', 'drone_name'],
    title: 'ShareResolved',
    description: 'Public resolve result — what a viewer needs to open the streams.'
} as const;

export const ShareSummarySchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['id', 'label', 'created_at', 'expires_at'],
    title: 'ShareSummary',
    description: 'Metadata for an active share (no token — only its hash is stored).'
} as const;

export const UserSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sub: {
            type: 'string',
            title: 'Sub'
        },
        issuer: {
            type: 'string',
            title: 'Issuer'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        is_admin: {
            type: 'boolean',
            title: 'Is Admin',
            default: false
        },
        creation_timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Creation Timestamp'
        },
        update_timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Update Timestamp'
        }
    },
    type: 'object',
    required: ['sub', 'issuer', 'email'],
    title: 'User'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;