// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { DroneListDronesResponse, DroneCreateDroneData, DroneCreateDroneResponse, DroneGetDroneData, DroneGetDroneResponse, DroneDeleteDroneData, DroneDeleteDroneResponse, MediaMediaAuthData, MediaMediaAuthResponse, UserListUsersResponse, UserMeResponse } from './types.gen';

export class DroneService {
    /**
     * List Drones
     * @returns DroneResponse Successful Response
     * @throws ApiError
     */
    public static listDrones(): CancelablePromise<DroneListDronesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/drone/'
        });
    }
    
    /**
     * Create Drone
     * @param data The data for the request.
     * @param data.requestBody
     * @returns DroneResponse Successful Response
     * @throws ApiError
     */
    public static createDrone(data: DroneCreateDroneData): CancelablePromise<DroneCreateDroneResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/drone/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Drone
     * @param data The data for the request.
     * @param data.droneId
     * @returns DroneResponse Successful Response
     * @throws ApiError
     */
    public static getDrone(data: DroneGetDroneData): CancelablePromise<DroneGetDroneResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/drone/{drone_id}',
            path: {
                drone_id: data.droneId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Drone
     * @param data The data for the request.
     * @param data.droneId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteDrone(data: DroneDeleteDroneData): CancelablePromise<DroneDeleteDroneResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/drone/{drone_id}',
            path: {
                drone_id: data.droneId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class MediaService {
    /**
     * Media Auth
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static mediaAuth(data: MediaMediaAuthData): CancelablePromise<MediaMediaAuthResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/media/auth',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UserService {
    /**
     * List Users
     * @returns User Successful Response
     * @throws ApiError
     */
    public static listUsers(): CancelablePromise<UserListUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/user/'
        });
    }
    
    /**
     * Me
     * @returns User Successful Response
     * @throws ApiError
     */
    public static me(): CancelablePromise<UserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/user/me'
        });
    }
}