// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { DronesListDronesResponse, DronesCreateDroneData, DronesCreateDroneResponse, DronesGetDroneData, DronesGetDroneResponse, DronesDeleteDroneData, DronesDeleteDroneResponse, DronesCreateShareData, DronesCreateShareResponse, DronesListSharesData, DronesListSharesResponse, DronesGetShareData, DronesGetShareResponse, DronesRevokeShareData, DronesRevokeShareResponse, HealthHealthResponse, SharesResolveShareData, SharesResolveShareResponse, UserListUsersResponse, UserMeResponse } from './types.gen';

export class DronesService {
    /**
     * List Drones
     * @returns DroneResponse Successful Response
     * @throws ApiError
     */
    public static listDrones(): CancelablePromise<DronesListDronesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/drones/'
        });
    }
    
    /**
     * Create Drone
     * @param data The data for the request.
     * @param data.requestBody
     * @returns DroneResponse Successful Response
     * @throws ApiError
     */
    public static createDrone(data: DronesCreateDroneData): CancelablePromise<DronesCreateDroneResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/drones/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Drone
     * @param data The data for the request.
     * @param data.droneId
     * @returns DroneResponse Successful Response
     * @throws ApiError
     */
    public static getDrone(data: DronesGetDroneData): CancelablePromise<DronesGetDroneResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/drones/{drone_id}',
            path: {
                drone_id: data.droneId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Drone
     * @param data The data for the request.
     * @param data.droneId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteDrone(data: DronesDeleteDroneData): CancelablePromise<DronesDeleteDroneResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/drones/{drone_id}',
            path: {
                drone_id: data.droneId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Share
     * @param data The data for the request.
     * @param data.droneId
     * @param data.requestBody
     * @returns ShareCreated Successful Response
     * @throws ApiError
     */
    public static createShare(data: DronesCreateShareData): CancelablePromise<DronesCreateShareResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/drones/{drone_id}/shares',
            path: {
                drone_id: data.droneId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Shares
     * @param data The data for the request.
     * @param data.droneId
     * @returns ShareSummary Successful Response
     * @throws ApiError
     */
    public static listShares(data: DronesListSharesData): CancelablePromise<DronesListSharesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/drones/{drone_id}/shares',
            path: {
                drone_id: data.droneId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Share
     * @param data The data for the request.
     * @param data.droneId
     * @param data.shareId
     * @returns ShareSummary Successful Response
     * @throws ApiError
     */
    public static getShare(data: DronesGetShareData): CancelablePromise<DronesGetShareResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/drones/{drone_id}/shares/{share_id}',
            path: {
                drone_id: data.droneId,
                share_id: data.shareId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Revoke Share
     * @param data The data for the request.
     * @param data.droneId
     * @param data.shareId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static revokeShare(data: DronesRevokeShareData): CancelablePromise<DronesRevokeShareResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/drones/{drone_id}/shares/{share_id}',
            path: {
                drone_id: data.droneId,
                share_id: data.shareId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class HealthService {
    /**
     * Health
     * @returns string Successful Response
     * @throws ApiError
     */
    public static health(): CancelablePromise<HealthHealthResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/health'
        });
    }
}

export class SharesService {
    /**
     * Resolve Share
     * @param data The data for the request.
     * @param data.token
     * @returns ShareResolved Successful Response
     * @throws ApiError
     */
    public static resolveShare(data: SharesResolveShareData): CancelablePromise<SharesResolveShareResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/shares/{token}',
            path: {
                token: data.token
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UserService {
    /**
     * List Users
     * @returns User Successful Response
     * @throws ApiError
     */
    public static listUsers(): CancelablePromise<UserListUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/user/'
        });
    }
    
    /**
     * Me
     * @returns User Successful Response
     * @throws ApiError
     */
    public static me(): CancelablePromise<UserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/user/me'
        });
    }
}