// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type {
    DronesListDronesResponse,
    DronesCreateDroneData,
    DronesCreateDroneResponse,
    DronesGetDroneData,
    DronesGetDroneResponse,
    DronesDeleteDroneData,
    DronesDeleteDroneResponse,
    UsersListUsersResponse,
} from './types.gen';

export class DronesService {
    /**
     * List Drones
     * Retrieve drones for the current user.
     * @returns DronePublic[] Successful Response
     * @throws ApiError
     */
    public static listDrones(): CancelablePromise<DronesListDronesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/drones/',
        });
    }

    /**
     * Create Drone
     * Register a new drone.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns DronePublic Successful Response
     * @throws ApiError
     */
    public static createDrone(data: DronesCreateDroneData): CancelablePromise<DronesCreateDroneResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/drones/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error',
            },
        });
    }

    /**
     * Get Drone
     * Get drone by ID.
     * @param data The data for the request.
     * @param data.droneId
     * @returns DronePublic Successful Response
     * @throws ApiError
     */
    public static getDrone(data: DronesGetDroneData): CancelablePromise<DronesGetDroneResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/drones/{drone_id}',
            path: {
                drone_id: data.droneId,
            },
            errors: {
                422: 'Validation Error',
            },
        });
    }

    /**
     * Delete Drone
     * Delete a drone.
     * @param data The data for the request.
     * @param data.droneId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteDrone(data: DronesDeleteDroneData): CancelablePromise<DronesDeleteDroneResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/drones/{drone_id}',
            path: {
                drone_id: data.droneId,
            },
            errors: {
                422: 'Validation Error',
            },
        });
    }
}

export class UsersService {
    /**
     * List Users
     * Retrieve users (admin sees all, regular user sees self).
     * @returns UserPublic[] Successful Response
     * @throws ApiError
     */
    public static listUsers(): CancelablePromise<UsersListUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
        });
    }
}
