// This file is auto-generated by @hey-api/openapi-ts

export type DroneCreate = {
    name: string;
};

export type DroneResponse = {
    id: string;
    name: string;
    secret_key: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
    stream_url?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ShareCreate = {
    label?: (string | null);
    ttl_hours?: number;
};

/**
 * Returned once at creation — the only time the plaintext token is exposed.
 */
export type ShareCreated = {
    id: string;
    token: string;
    expires_at: string;
};

/**
 * Public resolve result — what a viewer needs to open the streams.
 */
export type ShareResolved = {
    drone_id: string;
    drone_name: string;
};

/**
 * Metadata for an active share (no token — only its hash is stored).
 */
export type ShareSummary = {
    id: string;
    label: (string | null);
    created_at: string;
    expires_at: string;
};

export type User = {
    id?: string;
    sub: string;
    issuer: string;
    email: string;
    username?: (string | null);
    first_name?: (string | null);
    last_name?: (string | null);
    is_admin?: boolean;
    creation_timestamp?: string;
    update_timestamp?: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type DronesListDronesResponse = (Array<DroneResponse>);

export type DronesCreateDroneData = {
    requestBody: DroneCreate;
};

export type DronesCreateDroneResponse = (DroneResponse);

export type DronesGetDroneData = {
    droneId: string;
};

export type DronesGetDroneResponse = (DroneResponse);

export type DronesDeleteDroneData = {
    droneId: string;
};

export type DronesDeleteDroneResponse = (void);

export type DronesCreateShareData = {
    droneId: string;
    requestBody: ShareCreate;
};

export type DronesCreateShareResponse = (ShareCreated);

export type DronesListSharesData = {
    droneId: string;
};

export type DronesListSharesResponse = (Array<ShareSummary>);

export type DronesGetShareData = {
    droneId: string;
    shareId: string;
};

export type DronesGetShareResponse = (ShareSummary);

export type DronesRevokeShareData = {
    droneId: string;
    shareId: string;
};

export type DronesRevokeShareResponse = (void);

export type HealthHealthResponse = ({
    [key: string]: (string);
});

export type SharesResolveShareData = {
    token: string;
};

export type SharesResolveShareResponse = (ShareResolved);

export type UserListUsersResponse = (Array<User>);

export type UserMeResponse = (User);