// This file is auto-generated by @hey-api/openapi-ts

export type DroneCreate = {
    name: string;
};

export type DroneResponse = {
    id: string;
    name: string;
    creation_user_id: string;
    creation_timestamp: string;
    update_timestamp: string;
    stream_url?: (string | null);
};

export type DroneSecretResponse = {
    id: string;
    name: string;
    creation_user_id: string;
    creation_timestamp: string;
    update_timestamp: string;
    stream_url?: (string | null);
    secret: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ShareCreate = {
    label?: (string | null);
    ttl_hours?: number;
};

export type ShareCreatedResponse = {
    id: string;
    token: string;
    expiration_timestamp: string;
};

/**
 * The additional data that the user needs to view the streams.
 */
export type ShareResolvedResponse = {
    drone_id: string;
};

export type ShareResponse = {
    id: string;
    label: (string | null);
    creation_timestamp: string;
    expiration_timestamp: string;
};

export type User = {
    id?: string;
    sub: string;
    issuer: string;
    email: string;
    username?: (string | null);
    first_name?: (string | null);
    last_name?: (string | null);
    is_admin?: boolean;
    creation_timestamp?: string;
    update_timestamp?: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type DronesListDronesResponse = (Array<DroneResponse>);

export type DronesCreateDroneData = {
    requestBody: DroneCreate;
};

export type DronesCreateDroneResponse = (DroneSecretResponse);

export type DronesGetDroneData = {
    droneId: string;
};

export type DronesGetDroneResponse = (DroneResponse);

export type DronesDeleteDroneData = {
    droneId: string;
};

export type DronesDeleteDroneResponse = (void);

export type DronesRotateSecretData = {
    droneId: string;
};

export type DronesRotateSecretResponse = (DroneSecretResponse);

export type DronesCreateShareData = {
    droneId: string;
    requestBody: ShareCreate;
};

export type DronesCreateShareResponse = (ShareCreatedResponse);

export type DronesListSharesData = {
    droneId: string;
};

export type DronesListSharesResponse = (Array<ShareResponse>);

export type DronesGetShareData = {
    droneId: string;
    shareId: string;
};

export type DronesGetShareResponse = (ShareResponse);

export type DronesRevokeShareData = {
    droneId: string;
    shareId: string;
};

export type DronesRevokeShareResponse = (void);

export type HealthHealthResponse = ({
    [key: string]: (string);
});

export type SharesResolveShareData = {
    token: string;
};

export type SharesResolveShareResponse = (ShareResolvedResponse);

export type UserListUsersResponse = (Array<User>);

export type UserMeResponse = (User);