// This file is auto-generated by @hey-api/openapi-ts

export type DroneCreate = {
    name: string;
};

export type DroneResponse = {
    id: string;
    name: string;
    secret_key: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
    stream_url?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MediaMtxAuthRequestModel = {
    user: string;
    password: string;
    token: string;
    action: 'publish' | 'read';
    path: string;
    protocol: 'rtsp' | 'webrtc';
};

export type action = 'publish' | 'read';

export type protocol = 'rtsp' | 'webrtc';

export type User = {
    id?: string;
    sub: string;
    issuer: string;
    email: string;
    username?: (string | null);
    first_name?: (string | null);
    last_name?: (string | null);
    is_admin?: boolean;
    created_at?: string;
    updated_at?: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type DroneListDronesResponse = (Array<DroneResponse>);

export type DroneCreateDroneData = {
    requestBody: DroneCreate;
};

export type DroneCreateDroneResponse = (DroneResponse);

export type DroneGetDroneData = {
    droneId: string;
};

export type DroneGetDroneResponse = (DroneResponse);

export type DroneDeleteDroneData = {
    droneId: string;
};

export type DroneDeleteDroneResponse = (void);

export type MediaMediaAuthData = {
    requestBody: MediaMtxAuthRequestModel;
};

export type MediaMediaAuthResponse = (unknown);

export type UserListUsersResponse = (Array<User>);

export type UserMeResponse = (User);