#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${POSTGRES_BACKEND_USER} WITH PASSWORD '${POSTGRES_BACKEND_PASSWORD}';
    CREATE DATABASE ${POSTGRES_BACKEND_DB} OWNER ${POSTGRES_BACKEND_USER};

    CREATE USER ${KEYCLOAK_DB_USER} WITH PASSWORD '${KEYCLOAK_DB_PASSWORD}';
    CREATE DATABASE ${KEYCLOAK_DB} OWNER ${KEYCLOAK_DB_USER};
EOSQL
